services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  app:
    container_name: app
    build: .
    command: fastapi dev app/main.py --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    container_name: worker
    build: .
    command: celery --app app.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app

  beat:
    container_name: beat
    build: .
    command: celery --app app.celery_worker.celery_app beat --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app
      - worker

  flower:
    build: .
    command: celery --app app.celery_worker.celery_app flower --loglevel=info
    ports:
      - 5555:5555
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app
      - worker
      - beat

volumes:
  redis_data:
